version: '3'
services:
  app:
    build: .
    volumes:
      - ./mock-server:/usr/src/app/mock-server
    ports:
      - "5001:5001"
    command: ["node", "mock-server/server.js"] # Override ENTRYPOINT if needed
    # If you need to handle environment variables or other configurations, add them here.
